// import React from 'react'

// const carAbout = [
// {
// ToyotaCorolla:{
//     marka:'Toyota',
//     module:'Corolla',
//     info:{
//         Year:'2019',
//         Engine:'2.5L',
//         Color:'White',
//         TypeOfDrive:'Front',
//         Weight:'1525Kg',
//         FuelConsumption:'6,8L',
//         MaximumSpeed:'210km/h',
//         MaximumPower:'178Hp',
//         Fuel:'Petrol',
//         }
//   },
// VolkswagenJetta:{
//     marka:'Volkswagen',
//     module:'Jetta',
//     info:{
//         Year:'2016',
//         Engine:'1.6',
//         Color:'White',
//         TypeOfDrive:'Front',
//         Weight:'1525Kg',
//         FuelConsumption:'4,8L/100Km',
//         MaximumSpeed:'210km/h',
//         MaximumPower:'140Hp',
//         Fuel:'Diesel',
//         }
//   },
// FordFocus:{
//     marka:'Ford',
//     module:'Focus',
//     info:{
//         Year:'2012',
//         Engine:'1.8L',
       
      
//         Weight:'1525Kg',
//         FuelConsumption:'6,8L/100Km',
//         MaximumSpeed:'187km/h',
        
//         Fuel:'Diesel',
//         }
//   },
//   ToyotaCamry:{
//     marka:'Toyota',
//     module:'Camry',
//     info:{
//         Year:'2019',
//         Engine:'3.5L',
//         Weight:'1620kg',
//         FuelConsumption:'3,5L/100Km',
//         MaximumSpeed:'220km/h',
//         Fuel:'Petrol',
//         }
// },
// HondaAccord:{
//     marka:'Honda',
//     module:'Accord',
//     info:{
//         Year:'2020',
//         Engine:'2.0L',
//         Weight:'1455kg',
//         FuelConsumption:'7,6L/100Km',
//         MaximumSpeed:'229km/h',
//         Fuel:'Petrol',
//         }
// },
// FordFusion:{
//     marka:'Ford',
//     module:'Fusion',
//     info:{
//         Year:'2017',
//         Engine:'2.5 Duratec',
//         Weight:'1575kg',
//         FuelConsumption:'11L/100Km',
//         MaximumSpeed:'217km/h',
//         Fuel:'Petrol',
//         }
// },
// MercedesBenzEClassW213:{
//     marka:'Mercedes-Benz',
//     module:'E-Class (W213)',
//     info:{
//         Year:'2017',
//         Engine:'3.0',
//         Weight:'1580',
//         FuelConsumption:'8,8',
//         MaximumSpeed:'240',
//         Fuel:'Petrol',
//         }
// },
// BMWSeries:{
//     marka:'BMW',
//     module:'5 Series (530d)',
//     info:{
//         Year:'2020',
//         Engine:'3L',
//         Weight:'1820kg',
//         FuelConsumption:'7',
//         MaximumSpeed:'250',
//         Fuel:'Diesel',
//         }
// },
// LexusES:{
//     marka:'Lexus',
//     module:'ES',
//     info:{
//         Year:'2020',
//         Engine:'2.5',
//         Weight:'1650',
//         FuelConsumption:'7.9',
//         MaximumSpeed:'207',
//         Fuel:'Petrol',
//         }
// },
// HondaCivicTourer:{
//     marka:'Honda',
//     module:'Civic tourer',
//     info:{
//         Year:'2015',
//         Engine:'1.8',
//         Weight:'1355',
//         FuelConsumption:'6.2',
//         MaximumSpeed:'200',
//         Fuel:'Petrol',
//         }
// },
// VolkswagenGolfVariant:{
//     marka:'Volkswagen',
//     module:'Golf Variant',
//     info:{
//         Year:'2019',
//         Engine:'2.0',
//         Weight:'1490',
//         FuelConsumption:'5.6',
//         MaximumSpeed:'250',
//         Fuel:'Diesel',
//         }
// },
// HyundaiElantraTouring:{
//     marka:'Hyundai',
//     module:'Elantra Touring',
//     info:{
//         Year:'2019',
//         Engine:'2.0',
//         Weight:'1347',
//         FuelConsumption:'7.8',
//         MaximumSpeed:'190',
//         Fuel:'Petrol',
//         }
// },
// VolkswagenPassatVariant:{
//     marka:'Volkswagen',
//     module:'Passat Variant',
//     info:{
//         Year:'2018',
//         Engine:'1.8',
//         Weight:'1505',
//         FuelConsumption:'5,8',
//         MaximumSpeed:'232',
//         Fuel:'Petrol',
//         }
// },
// SubaruLegacyWagon:{
//     marka:'Subaru',
//     module:'Legacy Wagon',
//     info:{
//         Year:'2015',
//         Engine:'2.0',
//         Weight:'1488',
//         FuelConsumption:'9.1',
//         MaximumSpeed:'206',
//         Fuel:'Petrol',
//         }
// },
// AudiA4Avant:{
//     marka:'Audi',
//     module:'A4 Avant',
//     info:{
//         Year:'2019',
//         Engine:'2.0',
//         Weight:'1595',
//         FuelConsumption:'6.1',
//         MaximumSpeed:'236',
//         Fuel:'Petrol',
//         }
// },
// PorschePanameraSportTurismo:{
//     marka:'Porsche',
//     module:'Panamera Sport Turismo',
//     info:{
//         Year:'2018',
//         Engine:'4.0',
//         Weight:'2025',
//         FuelConsumption:'10,6',
//         MaximumSpeed:'259',
//         Fuel:'Petrol',
//         }
// },
// AudiA6Avant:{
//     marka:'Audi',
//     module:'A6 Avant',
//     info:{
//         Year:'2018',
//         Engine:'2.0',
//         Weight:'1802',
//         FuelConsumption:'6.5',
//         MaximumSpeed:'250',
//         Fuel:'Petrol',
//         }
// },
// VolvoV90:{
//     marka:'Volvo',
//     module:'V90',
//     info:{
//         Year:'2016',
//         Engine:'2.0',
//         Weight:'1834',
//         FuelConsumption:'6.7',
//         MaximumSpeed:'210',
//         Fuel:'Diesel',
//         }
// },
// ToyotaRAV4:{
//     marka:'Toyota',
//     module:'RAV4',
//     info:{
//         Year:'2018',
//         Engine:'2.5',
//         Weight:'1680',
//         FuelConsumption:'4.7',
//         MaximumSpeed:'180',
//         Fuel:'Petrol',
//         }
// },
// NissanRogue:{
//     marka:'Nissan',
//     module:'Rogue',
//     info:{
//         Year:'2018',
//         Engine:'2.5',
//         Weight:'1536kg',
//         FuelConsumption:'8.1',
//         MaximumSpeed:'180',
//         Fuel:'Petrol',
//         }
// },
// HyundaiTucson:{
//     marka:'Hyundai',
//     module:'Tucson',
//     info:{
//         Year:'2018',
//         Engine:'2.0',
//         Weight:'1425',
//         FuelConsumption:'8.1',
//         MaximumSpeed:'180',
//         MaximumPower:'155Hp',
//         Fuel:'Petrol',
//         }
// },
// HondaPilot:{
//     marka:'Honda',
//     module:'Pilot',
//     info:{
//         Year:'2017',
//         Engine:'3.5',
//         Weight:'1987',
//         FuelConsumption:'10.7',
//         MaximumSpeed:'190',
//         Fuel:'Petrol',
//         }
// },
// ChevroletTraverse:{
//     marka:'Chevrolet',
//     module:'Traverse',
//     info:{
//         Year:'2017',
//         Engine:'3.6',
//         Weight:'2147',
//         FuelConsumption:'10',
//         MaximumSpeed:'210',
//         Fuel:'Petrol',
//         }
// },
// FordExplorer:{
//     marka:'Ford',
//     module:'Explorer',
//     info:{
//         Year:'2015',
//         Engine:'2.3',
//         Weight:'2130',
//         FuelConsumption:'11.2',
//         MaximumSpeed:'183',
//         Fuel:'Petrol',
//         }
// },
// BMWX5:{
//     marka:'BMW',
//     module:'X5',
//     info:{
//         Year:'2015',
//         Engine:'4.4',
//         Weight:'2145',
//         FuelConsumption:'10.5',
//         MaximumSpeed:'250',
//         Fuel:'Petrol',
//         }
// },
// AudiQ5:{
//     marka:'Audi',
//     module:'Q5',
//     info:{
//         Year:'2020',
//         Engine:'2.0',
//         Weight:'1850',
//         FuelConsumption:'5.3',
//         MaximumSpeed:'222',
//         Fuel:'Diesel',
//         }
// },
// LexusRX:{
//     marka:'Lexus',
//     module:'RX',
//     info:{
//         Year:'2020',
//         Engine:'3.5',
//         Weight:'2210',
//         FuelConsumption:'5.3',
//         MaximumSpeed:'200',
//         Fuel:'Petrol',
//         }
// },
// VolkswagenGolf:{
//     marka:'Volkswagen',
//     module:'Golf',
//     info:{
//         Year:'2020',
//         Engine:'2.0',
//         Weight:'1463',
//         FuelConsumption:'6.6',
//         MaximumSpeed:'250',
//         Fuel:'Petrol',
//         }
// },
// HondaCivicHatchback:{
//     marka:'Honda',
//     module:'Civic Hatchback',
//     info:{
//         Year:'2017',
//         Engine:'2.0',
//         Weight:'1380',
//         FuelConsumption:'7.7',
//         MaximumSpeed:'272',
//         Fuel:'Petrol',
//         }
// },
// ToyotaCorollaHatchback:{
//     marka:'Toyota',
//     module:'Corolla Hatchback',
//     info:{
//         Year:'2017',
//         Engine:'1.8',
//         Weight:'1380',
//         FuelConsumption:'3.6',
//         MaximumSpeed:'180',
//         Fuel:'Petrol',
//         }
// },
// VolkswagenGolfGTI:{
//     marka:'Volkswagen',
//     module:'Golf GTI',
//     info:{
//         Year:'2017',
//         Engine:'2.0',
//         Weight:'1408',
//         FuelConsumption:'6.3',
//         MaximumSpeed:'248',
//         Fuel:'Petrol',
//         }
// },
// Mazda3Hatchback:{
//     marka:'Mazda3',
//     module:'Hatchback',
//     info:{
//         Year:'2011',
//         Engine:'2.0',
//         Weight:'1243',
//         FuelConsumption:'7.6',
//         MaximumSpeed:'196',
//         Fuel:'Petrol',
//         }
// },
// Hyundaii30N:{
//     marka:'Hyundai',
//     module:'i30 N',
//     info:{
//         Year:'2017',
//         Engine:'2.0',
//         Weight:'1950',
//         FuelConsumption:'7.1',
//         MaximumSpeed:'250',
//         Fuel:'Petrol',
//         }
// },
// AudiA3Sportback:{
//     marka:'Audi',
//     module:'A3 Sportback',
//     info:{
//         Year:'2016',
//         Engine:'2.0',
//         Weight:'1740',
//         FuelConsumption:'5.7',
//         MaximumSpeed:'242',
//         Fuel:'Petrol',
//         }
// },
// MercedesBenzAClassHatchback:{
//     marka:'Mercedes-Benz',
//     module:'A-Class Hatchback',
//     info:{
//         Year:'2016',
//         Engine:'2.0',
//         Weight:'1740',
//         FuelConsumption:'7.4',
//         MaximumSpeed:'200',
//         Fuel:'Petrol',
//         }
// },
// BMW1Series:{
//     marka:'BMW',
//     module:'1 Series',
//     info:{
//         Year:'2016',
//         Engine:'2.0',
//         Weight:'1375',
//         FuelConsumption:'5.7',
//         MaximumSpeed:'230',
//         Fuel:'Petrol',
//         }
// },
// }
// ]




// const CarAbout = () => {
//     return <></>; 
//   };
  
//   export { carAbout, CarAbout };